import Image from "next/image";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Main from "../components/Main";

export default function Home() {
	return (
		<div>
			<Head>
				<title>GMD</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Main />
			
		</div>
	);
}
